layout-location: "DefaultLayout"                # The location of the layout file ImGui writes to
load-layout: true                               # Whether to load the layout file ImGui writes to
save-layout: true                               # Whether to automatically save to the layout file ImGui writes to
icon: "udf-panel.png"                           # The location of the window icon image
width: 100                                      # Width of the window in pixels. Panel size should be specified in its config, this value will not be honored
height: 100                                     # Height of the window in pixels. Panel size should be specified in its config, this value will not be honored
fullscreen: false                               # Enable or disable fullscreen mode
window-name: UntitledDesktop Flow Panel         # The name of the window
resizeable: true                               # Can the window be resized
transparent-surface: true                       # Transparency for the render surface, platform dependant, ImGuiCol_WindowBg.w controls this
hidden: false                                   # The default visibility of the window
focused: false                                  # Default focused state
size-limits: [ -1, -1, -1, -1 ]                 # Limit the size of the Window in vec4 format: x = min x, y = min y, z = max x, w = max y. -1 = no limit
aspect-ratio-size-limit: [ -1, -1 ]             # Limit the size of the Window using an aspect ratio x/y. -1 = no limit
decorated: false                                # Enable or disable window decorations
maximised: false                                # Enable or disable window maximisation
